### ISSUE TITLE
ead_value: Use separate EADs

### ISSUE THREAD

**Issue by chrysn** [ace-wg/ace-edhoc-oscore-profile#7]
Packing the token into the EAD as <<{0: 'the-token'}>> adds at least 3 bytes (more for tokens >24 byte) to the token, likewise to the session ID.

@gselander, @marco-tiloca-sics and I discussed a few options back and forth, and given we want to support arbitrary byte string tokens (not only CWTs), it may get smaller, but not by much without sacrificing the clear distinction between a session ID and a token. (We've played with the session ID being a CCS, and with being some kind of key ID, but that doesn't really make the double encapsulation of the token go away).

In the end, we've concluded that for this case it is justified to use one EAD value for a session ID, and a different one (not from 1+0, maybe even from 1+2) for an EAD indicating a session ID. The one bit we take out of that makes up for at least 3 bytes in the payload, and it's not like this is requesting two 1+0 values.

**Comment by gselander** [comment]
There are separate EADs defined in -06. Does that address this issue?

**Comment by gselander** [comment]
Marco's comment: Can be closed.
